# Generated by Django 6.0.2 on 2026-02-23 03:14

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#C8572A', help_text='Color HEX, ej: #C8572A', max_length=7)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=eventos.models.imagen_evento_path, verbose_name='Imagen del evento')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa de imagen (alternativa a subir archivo)')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora del evento')),
                ('lugar', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('detalle_lugar', models.CharField(blank=True, max_length=300, verbose_name='Dirección o detalle del lugar')),
                ('ciudad', models.CharField(default='Bogotá', max_length=100)),
                ('abierto', models.BooleanField(default=True, verbose_name='Inscripciones abiertas')),
                ('destacado', models.BooleanField(default=False, verbose_name='Evento destacado')),
                ('gratuito', models.BooleanField(default=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en COP si no es gratuito', max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
    ]
