# Generated by Django 6.0.2 on 2026-03-04 23:25

import django.db.models.deletion
import eventos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='recurrencia',
            field=models.CharField(blank=True, choices=[('ninguna', 'Sin recurrencia'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='ninguna', max_length=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de video (YouTube, Vimeo…)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#C8572A', max_length=7),
        ),
        migrations.AlterField(
            model_name='evento',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.categoria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='detalle_lugar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.imagen_evento_path),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FechaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nota', models.CharField(blank=True, help_text='Ej: Sesión 2, Cierre, etc.', max_length=200)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_adicionales', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Fecha adicional',
                'verbose_name_plural': 'Fechas adicionales',
                'ordering': ['fecha'],
            },
        ),
    ]
