# Generated by Django 6.0.2 on 2026-03-06 00:23

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_fecha_alter_evento_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, help_text='Archivo de video (sube a Cloudinary automáticamente)', null=True, upload_to=eventos.models.video_evento_path),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL externa de video (YouTube, Vimeo, etc.)'),
        ),
    ]
