# Generated by Django 6.0.2 on 2026-03-06 17:34

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_video_alter_evento_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=eventos.models.imagen_evento_path),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, help_text='Archivo de video (sube a Cloudinary automáticamente)', max_length=500, null=True, upload_to=eventos.models.video_evento_path),
        ),
    ]
