# Generated by Django 6.0.2 on 2026-02-23 03:14

import django.db.models.deletion
import entrevistas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrevistado', models.CharField(max_length=200, verbose_name='Nombre del entrevistado')),
                ('rol', models.CharField(max_length=200, verbose_name='Rol / descripción del entrevistado')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('resumen', models.CharField(max_length=500)),
                ('descripcion_larga', models.TextField(verbose_name='Descripción completa')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=entrevistas.models.imagen_entrevista_path)),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa de imagen')),
                ('audio_archivo', models.FileField(blank=True, null=True, upload_to=entrevistas.models.audio_path, verbose_name='Archivo de audio (MP3, WAV, OGG)')),
                ('audio_url', models.URLField(blank=True, help_text='URL externa de audio (SoundCloud, Spotify, etc.)')),
                ('duracion', models.CharField(blank=True, help_text='Duración en formato MM:SS. Ej: "38:24"', max_length=10)),
                ('categoria', models.CharField(choices=[('MAESTROS', 'Maestros'), ('VOCES NUEVAS', 'Voces Nuevas'), ('INTERNACIONAL', 'Internacional'), ('EXPERIMENTALES', 'Experimentales')], default='MAESTROS', max_length=20)),
                ('categoria_color', models.CharField(default='#C8572A', max_length=7)),
                ('publicada', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
