# Generated by Django 6.0.2 on 2026-02-23 03:14

import django.db.models.deletion
import noticias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('resumen', models.TextField(max_length=500)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to=noticias.models.imagen_noticia_path)),
                ('imagen_portada_url', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('CRÓNICA', 'Crónica'), ('GUÍA', 'Guía'), ('EVENTO', 'Evento'), ('REPORTAJE', 'Reportaje')], default='CRÓNICA', max_length=20)),
                ('categoria_color', models.CharField(default='#C8572A', max_length=7)),
                ('tiempo_lectura', models.PositiveSmallIntegerField(default=5, help_text='Tiempo estimado de lectura en minutos')),
                ('publicada', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parrafo', 'Párrafo'), ('subtitulo', 'Subtítulo'), ('imagen', 'Imagen'), ('cita', 'Cita')], max_length=15)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=noticias.models.imagen_bloque_path)),
                ('src', models.URLField(blank=True)),
                ('pie', models.CharField(blank=True, max_length=300)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='noticias.noticia')),
            ],
            options={
                'verbose_name': 'Bloque de contenido',
                'verbose_name_plural': 'Bloques de contenido',
                'ordering': ['orden'],
            },
        ),
    ]
