# Generated by Django 6.0.2 on 2026-02-23 03:14

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('CUENTERO', 'Cuentero'), ('ADMIN', 'Administrador')], db_index=True, default='USUARIO', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=usuarios.models.avatar_upload_path, verbose_name='Foto de perfil')),
                ('gustos', models.JSONField(blank=True, default=list, help_text='Lista de categorías de interés. Ej: ["CUENTO","FESTIVAL"]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_union', models.DateTimeField(auto_now_add=True, verbose_name='Miembro desde')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_union'],
            },
        ),
        migrations.CreateModel(
            name='EventoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('GUARDADO', 'Guardado'), ('ASISTIDO', 'Asistido')], default='GUARDADO', max_length=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardado_por', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento guardado',
                'verbose_name_plural': 'Eventos guardados',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
